### ISSUE TITLE
Site is not working

### ISSUE THREAD

**Issue by splpaul** [adamrutter/pywal-themes-preview#4]
Site loads and seems to work perfectly but the colors of the color themes are not rendering. All I see is this box :
"😀 adam   📁 ~
> wal --theme base16-3024
[I] theme: Set theme to base16-3024.json.
[I] sequences: Set terminal colors.

[I] export: Exported all files.
[I] export: Exported all user files.
[I] reload: Reloaded environment.

😀 adam   📁 ~
> ls
bin
documents
downloads
games
pictures
videos

😀 adam   📁 ~
> sudo pacman -Syu"

**Comment by adamrutter** [comment]
That's odd, it's working fine for me. What OS/browser are you using? Any errors in the browser's console?

**Comment by splpaul** [comment]
Well, the problem was darkreader apparently.
